# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d065635e9d5208d53ca7360c2272d39003a62c2a1b257f64ffd90447ad200b4edbedb3613a48575963d0001147fe3adacbc550fbfab9589ac0421add3ffef4ee

test:
  secret_key_base: c28bca7ef1ff8e49022b6eb7a4c52883044a286137ffabc1f7ab2a7d66b123f7442df946b5150d5628bb9279c55e87dd26da1741186533e0719a60cb82523164

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
